### ISSUE TITLE
QueryDict __getitem__ wrong type

### ISSUE THREAD

**Issue by StefanBrand** [typeddjango/django-stubs#1010]
# Bug report

## What's wrong

In our code base I get `Type of "self.request.query_params["start_date"]" is "str | List[object]"` after upgrading `django-stubs` from `1.8.0` to `1.12.0`.

Reproducible example:
```py
from django.http import QueryDict


query_params = QueryDict()
reveal_type(query_params["foo"])
```
`Type of "query_params["foo"]" is "str | List[object]"`

According to [Django docs](https://docs.djangoproject.com/en/4.0/ref/request-response/#django.http.QueryDict.__getitem__), `QueryDict.__getitem__` always returns one value, never a list:

> Returns the value for the given key. If the key has more than one value, it returns the last value.

## How is that should be

Type of "query_params["foo"]" should be  "str"

## System information

- OS: `python:3.9.1` Docker image
- `python` version: 3.9.1
- `django` version: 4.0.1
- `mypy` version: 0.931
- `django-stubs` version: 1.12.0
~~- `django-stubs-ext` version:~~

**Comment by sobolevn** [comment]
СС @intgr

**Comment by intgr** [comment]
> According to [Django docs](https://docs.djangoproject.com/en/4.0/ref/request-response/#django.http.QueryDict.__getitem__), QueryDict.\_\_getitem__ always returns one value, never a list:
>
> > Returns the value for the given key. If the key has more than one value, it returns the last value.

You would think so, but actually:

```python
In [6]: from django.http.request import QueryDict
In [7]: q = QueryDict(mutable=True)

In [8]: q.setlist('foo', ['value'])
In [9]: q['foo']
Out[9]: 'value'

In [10]: q.setlist('bar', [])
In [11]: q['bar']
Out[11]: []                # <-- !?!?
```

I would argue this is a bug in Django, but I don't think this has been reported upstream.

#909 added the hint that `QueryDict.__getattr__` may return list, and #925 added the `_ImmutableQueryDict` hack to work around the common usages where lists shouldn't occur. See https://github.com/typeddjango/django-stubs/pull/925#discussion_r851922533 for relevant discussion.

> Type of "self.request.query_params["start_date"]" is "str | List[object]"

It looks like you're using django-rest-framework, `query_params` comes from djangorestframework-stubs.

This can be fixed by using `_ImmutableQueryDict` there. I have opened a pull request: https://github.com/typeddjango/djangorestframework-stubs/pull/237

(But if this continues to cause problems, personally I'm not opposed to reverting the complexity created for `_ImmutableQueryDict` and going back to the un-pedantic but "wrong" type hint that `__getattr__` returns `str`.)

**Comment by intgr** [comment]
Cc: @sterliakov
