### ISSUE TITLE
Form.data typed as Mapping instead of MultiValueDict

### ISSUE THREAD

**Issue by mschoettle** [typeddjango/django-stubs#1397]
# Bug report

## What's wrong

I have a `Form` where I wanted to call `self.data.copy()` and get the following type error:

> "Mapping[str, Any]" has no attribute "copy" 

Looking at the Django code and the type of `form.data` at runtime it is instantiated with an empty `MultiValueDict` in `BaseForm.__init__` and `QueryDict` at runtime (a sub-class of `MultiValueDict`).

The current type hints are here:

* https://github.com/typeddjango/django-stubs/blob/master/django-stubs/forms/forms.pyi#L22
* https://github.com/typeddjango/django-stubs/blob/master/django-stubs/forms/utils.pyi#L12

## How is that should be

I could definitely be wrong but think that it should be typed as `MultiValueDict` instead of `Mapping`.

If so, I am happy to create a PR for it.

## System information

- OS:
- `python` version: 3.10.10
- `django` version: 4.1.7
- `mypy` version: 1.1.1
- `django-stubs` version: 1.15.0
- `django-stubs-ext` version: 0.7.0?

**Comment by adamchainz** [comment]
I think the stub is correct, since you can pass any dict-like object to a form for validation. You probably see `QueryDict` at runtime because you're passing in `request.POST`, but Django also allows vanilla dictionaries or any other kind of mapping.

Therefore Mypy is correctly flagging `.copy()` as incorrect. As an alternative, you can use `copy.copy` (the copy module), or you could create a form subclass that ensures `data` is `MultiValueDict`.
