### ISSUE TITLE
Abstract model inheritance

### ISSUE THREAD

**Issue by Saymmic** [typeddjango/django-stubs#212]
# Bug report

## What's wrong
When the concrete model inherits from the abstract model mypy wants me to annotate fields.

## How is that should be
It should know that this is an inheritance and annotate fields.

## System information

- OS:
- `python` version: 3.8
- `django` version: 2.1
- `mypy` version: 0.720
- `django-stubs` version: 1.1.0

**Comment by adamantike** [comment]
I have only been able to reproduce this issue when the plugin is installed but not [configured](https://github.com/typeddjango/django-stubs#installation).

The [`django_contrib_gis_base_model_mixin_inheritance` test](https://github.com/typeddjango/django-stubs/blob/1b8c1b50a287f4b78d78165c8387f0a4976a5972/tests/typecheck/models/test_inheritance.yml#L90) covers a similar scenario.

**Comment by flaeppe** [comment]
Since the information is quite sparse here, I'm going to close this issue. As already pointed out, there's quite a bit of tests related to abstract models in [tests/typecheck/models/test_inheritance.yml](https://github.com/typeddjango/django-stubs/blob/348ae5f4896f023fa89d6bbc6e2b20de0f56f311/tests/typecheck/models/test_inheritance.yml)

Feel free to provide a repro case and we'll reopen.
