### ISSUE TITLE
BaseDatabaseWrapper.SchemaEditorClass has incorrect type

### ISSUE THREAD

**Issue by rvinzent** [typeddjango/django-stubs#553]
# Bug report

## What's wrong

`django.db.backends.base.BaseDatabaseWrapper` has incorrectly defined `SchemaEditorClass` property.

This error is raised when overriding the class
```
error: Incompatible types in assignment (expression has type "Type[MySchemaEditor]", base class "BaseDatabaseWrapper" defined the type as "Optional[BaseDatabaseSchemaEditor]")
```

## How is that should be

The type should be `Optional[Type[BaseDatabaseSchemaEditor]]` because the property is a class, not an instance of `BaseDatabaseSchemaEditor`.

## System information

- OS: MacOS
- `python` version: 3.9
- `django` version: 3.1
- `mypy` version: 0.790
- `django-stubs` version: 1.7.0

**Comment by adamchainz** [comment]
Fixed in #612.

**Comment by rvinzent** [comment]
> Fixed in #612.

@adamchainz are you sure this is the same issue? The linked fix adds a new method definition but doesn't address the incorrect typing on the one in this issue

**Comment by adamchainz** [comment]
Isn’t this the line you were looking for?

https://github.com/typeddjango/django-stubs/pull/612/files#diff-b7fe04c8e35ac07ecc22682f8b72c3610500ec8f0d60a30bca745f1caca6d315R28

Now on master: https://github.com/typeddjango/django-stubs/blob/7bce5c2081ef2b7bc84daca68d0f3d11a38bdf66/django-stubs/db/backends/base/base.pyi#L26

(It shouldn't be `Optional`, since `None` is not allowed)

**Comment by rvinzent** [comment]
Looks good! For some reason I was seeing a different PR earlier
