### ISSUE TITLE
Get rid of `ValuesQuerySet`

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#608]
Problems with `QuerySet` / `ValuesQuerySet` separation:
- There are a lot of places, where we use `QuerySet` annotation, so `ValuesQuerySet` is not allowed there. 
- We cannot simply change it, because `_BaseQuerySet` is not enough for small portion of cases
- `T` type var has `models.Model` bound, which stops us from annotating thing with, for example, `QuerySet[SomeTypedDict]`, which is valid when we use `.values` and `SomeTypedDict` represents the final result of this call

**Comment by sobolevn** [comment]
Related: https://github.com/typeddjango/django-stubs/pull/603/commits/6522f30cdb9027483f46d77167394c84eb7b7f4b

**Comment by syastrov** [comment]
But should a `QuerySet` where `.values` was called still have the original `Model` in its type?

It might be relevant if I were to call `.filter` after calling `.values` to know which type of `Model` is being queried so that the type-checker can generate an error if I filtered on an invalid field.

If Django hadn't allowed users to "flaunt their individualism", this would be a lot simpler :)

https://docs.djangoproject.com/en/3.2/ref/models/querysets/#django.db.models.query.QuerySet.values
> The people who made Django prefer to put all the SQL-affecting methods first, followed (optionally) by any output-affecting methods (such as values()), but it doesn’t really matter. This is your chance to really flaunt your individualism.

Also, another weird edge-case is that you can call `.bulk_create` after calling `.values`. There, knowledge of the `Model` is also useful for type-checking.

However, we can just decide to go after simplicity rather than absolute correctness, and accept that these uncommon patterns of use are likely to result in less type-checking or false positives.

**Comment by sobolevn** [comment]
I thing that we can try to add the second type argument dynamically to `QuerySet` instance when we need to (basically after `.values` / similar calls). This way, we would still have pretty user-facing API like `QuerySet[MyModel]` and all the features of `ValuesQuerySet`.

Later, we can use `TypeArgTuple` to represent this natively using variadic generics.

**Comment by syastrov** [comment]
That would be nice. Would you check the behavior in other type-checkers if you haven't provided all the type parameters?
It would be pretty nasty if you always got an error there.

I'm not sure I see how using variadic generics will help? It seems like we have some fixed number of type parameters, but we should allow some defaults for them if not provided (except that is not currently possible).

**Comment by syastrov** [comment]
I am afraid that making 2 generic parameters to QuerySet and hacking it in the mypy plugin to default the second parameter to the first one will make it even less likely that django-stubs will work in other type-checkers than mypy.
(I actually implemented this before mkurnikov changed QuerySet back to take one type param :)).

Are there any other options? I'll try to list some:

1. Start up a discussion / PEP about making default type parameters on `typing-sig`.
Pros: Fixing the root of the problem and working in all type checkers. We can remove `ValuesQuerySet`
Cons: Likely to take a lot of time and effort, and will not necessarily be accepted

2. Add second parameter to `QuerySet`, and don't implement this hackery about defaulting the second type parameter in the plugin.
Pros: It's explicit/standard and works across type checkers. Doesn't require hacks. We can remove `ValuesQuerySet`
Cons: A lot of people would find it annoying to change their code, but it's a one-time fix, assuming we settle on this. To prevent people from writing `QuerySet[MyModel, MyModel]` all over the place, we can provide an alias in `django_stubs_ext`. e.g. `ModelQuerySet = QuerySet[_T, _T]`. Then it's just `ModelQuerySet[MyModel]`.

3. Rename it to `_ValuesQuerySet`, since it is a private implementation detail, and leave it as is.
Pros: Simple change, and hopefully won't break anyone's code.
Cons: We now don't have a way to type-annotate the querysets returning e.g. tuples/dicts in user-code, `_ValuesQuerySet` is private/doesn't exist at runtime. We could provide a public alias to this though in `django_stubs_ext`, e.g. `ValuesQuerySet = _ValuesQuerySet[_T, _Row]`.

I think I vote for (3). What do you think @sobolevn?

> There are a lot of places, where we use QuerySet annotation, so ValuesQuerySet is not allowed there.

It's a subclass, so I don't know why it wouldn't be allowed. Do you have any examples?

*Edit*: Ah, I see, we have to change the current hierarchy by having `ValuesQuerySet` inherit directly from `QuerySet` and removing `_BaseQuerySet`.

> T type var has models.Model bound, which stops us from annotating thing with, for example, QuerySet[SomeTypedDict], which is valid when we use .values and SomeTypedDict represents the final result of this call

I think we should use 2 generic parameters to allow this, so if you didn't care which model it was about, you could use the annotation: `QuerySet[Any, SomeTypedDict]`

**Comment by syastrov** [comment]
I've given idea (3) a shot: https://github.com/typeddjango/django-stubs/pull/654
I had to add a type-ignore on the `_ValuesQuerySet` class declaration or I got an "Cannot create a consistent method resolution order (MRO)" error (I believe due to inheriting from `Container`).

**Comment by sobolevn** [comment]
Yes, I agree that this seems like the best solution.

**Comment by sobolevn** [comment]
> Start up a discussion / PEP about making default type parameters on typing-sig.

I have already seen this discussed, but I cannot find the link.

**Comment by sobolevn** [comment]
We can consider this done! Thanks to @syastrov 🎉
