### ISSUE TITLE
[Question] What is an alternative to isinstance(obj, QuerySet)?

### ISSUE THREAD

**Issue by martin-thoma** [typeddjango/django-stubs#704]
I've recently got 

> Parameterized generics cannot be used with class or instance checks

with `django-stubs==1.9.0` for `isinstance(obj, QuerySet)` when I run mypy over the code.

What is the recommended way to do it?

**Comment by sobolevn** [comment]
This is because `QuerySet` is now `= _QuerySet[_T, _T]` from https://github.com/typeddjango/django-stubs/commit/cfd69c0acc4bb3c282cab4a411b014afe280d359#diff-389fe7d7dcfb77ddaac87c1f3bdc196f3ef0ca33b8047c6638a15f3a3db21b56R170

We can try to alias it as `QuerySet = _QuerySet` it should be the same thing, but without subscription.

@MT-Cash can you please try that?

**Comment by martin-thoma** [comment]
From where should I import `_QuerySet`?

**Comment by sobolevn** [comment]
You cannot import `_QuerySet`, because it is our only-in-stubs thing. You can send a Pr with the `[_T, _T]` removed from this line: https://github.com/typeddjango/django-stubs/commit/cfd69c0acc4bb3c282cab4a411b014afe280d359#diff-389fe7d7dcfb77ddaac87c1f3bdc196f3ef0ca33b8047c6638a15f3a3db21b56R170

It might help.

**Comment by jerch** [comment]
Kinda stumbled over the same issue and can confirm, that removing `[_T, _T]` solved it for me.

Created PR #794.
