### ISSUE TITLE
GSoC 2022 😀🌳

### ISSUE THREAD

**Issue by Bhavya-official** [typeddjango/django-stubs#917]
I am Bhavya Agrawal, a passionate GSoC participant. I want to work on one of the [listed](https://code.djangoproject.com/wiki/SummerOfCode2022) project ideas `Typed Django` for the Django framework.
It sounds interesting to work on.

I know some basics in mypy and am proficient in python. 
As a pioneer in the community, please guide me on where I will find beneficial content regarding this idea. How can I start? What are the other things to be known? And lots of stuff if you aware.

```Please reply asap.```

Thank you.

**Comment by sobolevn** [comment]
Hi, @Bhavya-official! 

Thanks a lot for your proposal! I would love to see this happen.
But, Google decided that I am not able to participate in GSoC anymore, because I am Russian.

And since this organization belives that it is fine to ban people based on their nationality, I don't want to be associated with it in any manner.

I am really sad that because of these unlawful actions inocent people like you are affected.
I hope that you will be able to find some other project to work on. 
Please, feel free to ask for help during your journey! I would be glad to 🙂
