### ISSUE TITLE
Incorrect `BaseCreateView.object` annotation

### ISSUE THREAD

**Issue by sondrelg** [typeddjango/django-stubs#986]
# Bug report

## What's wrong

An example of a `CreateView` looks like this (from the Django docs)

```python
from django.views.generic.edit import CreateView
from myapp.models import Author

class AuthorCreateView(CreateView):
    model = Author
    fields = ['name']
```

but the model attribute on the `BaseCreateView` that `CreateView` inherits from is currently defined as `None` [here](https://github.com/typeddjango/django-stubs/blob/master/django-stubs/views/generic/edit.pyi#L52).

## How is that should be

I think object should be annotated something like this

```python
class BaseCreateView(ModelFormMixin[_M, _ModelFormT], ProcessFormView):
    object: Optional[_M]
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
```

**Comment by sondrelg** [comment]
I think (though I'm not 100% sure) that [this](https://github.com/typeddjango/django-stubs/blob/master/django-stubs/views/generic/edit.pyi#L60) and the other base view object annotations should also be the same.

**Comment by sterliakov** [comment]
The initial reasoning was like the following:

* `CreateView`: `object` is [set](https://github.com/django/django/blob/main/django/views/generic/edit.py#L135=) only after `form_valid()` call. So it is available only for a small subset of standard methods: `post` and `form_valid` after `super` calls plus `get_redirect_url`.  It would be very odd to annotate it as `_M` (because it's missing almost always), but `_M | None`, as you suggest, looks like a good solution here.
* `UpdateView` and `DeleteView`: both have `self.object` set to `self.get_object()` value in `post` and `get` before `super()` call. Thus it is almost always available. (note: `get_object` is hinted to return `_M`, so `Optional` here seems unreasonable).

Personally, I think that `CreateView` should be updated and other should remain as is. If you have any other thoughts, please elaborate a bit more on this.

**Comment by sondrelg** [comment]
That sounds good to me @sterliakov 👍
